name: 'Setup'

runs:
  using: "composite"
  steps:
    - name: Checkout submodules
      shell: bash
      run: git submodule update --init --recursive
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: yarn install --frozen-lockfile
      shell: bash
