name: Continuous Integration

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/setup
      - run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/setup
      - run: yarn test:unit
