name: Continuous Integration

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/setup/action.yml@workflow
      - run: yarn lint
      - run: yarn test:unit

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/setup/action.yml@workflow
      - run: yarn lint
      - run: yarn test:unit
