name: Continuous Integration

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: Dzuelu/discord-bot/.github/setup/action.yml
      - run: yarn lint
      - run: yarn test:unit

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: Dzuelu/discord-bot/.github/setup/action.yml
      - run: yarn lint
      - run: yarn test:unit
